server:
   port: 8088
mybatis:
   type-aliases-package: com.zb.blog.pojo
   mapper-locations: classpath:mapper/*.xml
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/blog01?characterEncoding=utf-8&serverTimezone=UTC&useUnicode=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver