package com.zb.blog.dao;

import com.zb.blog.pojo.Support;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support
     *
     * @mbggenerated
     */
    int insert(Support record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support
     *
     * @mbggenerated
     */
    int insertSelective(Support record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support
     *
     * @mbggenerated
     */
    Support selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Support record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Support record);
}