package com.zb.blog.pojo;

import java.io.Serializable;

public class Support implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support.supporter_id
     *
     * @mbggenerated
     */
    private Integer supporterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table support
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support.id
     *
     * @return the value of support.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support.id
     *
     * @param id the value for support.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support.supporter_id
     *
     * @return the value of support.supporter_id
     *
     * @mbggenerated
     */
    public Integer getSupporterId() {
        return supporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support.supporter_id
     *
     * @param supporterId the value for support.supporter_id
     *
     * @mbggenerated
     */
    public void setSupporterId(Integer supporterId) {
        this.supporterId = supporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support.article_id
     *
     * @return the value of support.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support.article_id
     *
     * @param articleId the value for support.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", supporterId=").append(supporterId);
        sb.append(", articleId=").append(articleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}